---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
metadata:
  name: kubeadm-cluster-configuration
networking:
  podSubnet: $POD_CIDR
  serviceSubnet: $SERVICE_CIDR
controllerManager:
  extraArgs:
    allocate-node-cidrs: \"true\"
    cluster-cidr: $POD_CIDR
