---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
metadata:
  name: kubeadm-init-configuration
nodeRegistration:
  criSocket: unix://$CRI_SOCKET
  kubeletExtraArgs:
    max-pods: '"1000"'
    node-labels: elotl.co/milpa-worker=""
