apiVersion: v1
kind: Pod
metadata:
  name: kotsadm-migrations
spec:
  restartPolicy: OnFailure
  containers:
  - name: kotsadm-migrations
    image: kotsadm/kotsadm-migrations:v0.9.14
    env:
    - name: SCHEMAHERO_DRIVER
      value: postgres
    - name: SCHEMAHERO_SPEC_FILE
      value: /tables
    - name: SCHEMAHERO_URI
      valueFrom:
        secretKeyRef:
          name: kotsadm-postgres
          key: uri
