---
kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
nodeRegistration:
  name: $NODE_NAME
  taints: []
  criSocket: unix://$CRI_SOCKET
  kubeletExtraArgs:
    node-ip: $PRIVATE_ADDRESS
    cloud-provider: aws
    network-plugin: kubenet
    non-masquerade-cidr: 0.0.0.0/0
    max-pods: "1000"
discovery:
  bootstrapToken:
    token: $KUBEADM_TOKEN
    apiServerEndpoint: $API_SERVICE_ADDRESS
    caCertHashes:
    - $KUBEADM_TOKEN_CA_HASH
