---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v$KUBERNETES_VERSION
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
useHyperKubeImage: true
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  podSubnet: $POD_CIDR
  serviceSubnet: $SERVICE_CIDR
apiServer:
  extraArgs:
    cloud-provider: aws
    enable-admission-plugins: DefaultStorageClass
    service-node-port-range: "80-60000"
  certSANs:
    - "$PRIVATE_ADDRESS"
controllerManager:
  extraArgs:
    cloud-provider: aws
    configure-cloud-routes: \"true\"
    address: 0.0.0.0
