---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
metadata:
  name: kubeadm-cluster-configuration
kubernetesVersion: v$KUBERNETES_VERSION
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
useHyperKubeImage: true
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  serviceSubnet: $SERVICE_CIDR
apiServer:
  extraArgs:
    service-node-port-range: "80-60000"
  certSANs:
  - "$PRIVATE_ADDRESS"
